cache_timeout arg removed from send_file
cache_timeout argument is removed from flask modules called send_file(). This argument was causing the following error in the Flask 2.2.3 

TypeError: send_file() got an unexpected keyword argument 'cache_timeout'